"""Render the RM-finalized offer into a premium, IDBI-branded PDF.

Deterministic engine owns every number (passed in from the validated offer); the
LLM only supplies the intro + benefit wording. WeasyPrint renders web/templates/
offer.html. Needs native pango/cairo (run with DYLD_FALLBACK_LIBRARY_PATH on mac).
"""
from __future__ import annotations

import os
from datetime import date

from jinja2 import Environment, FileSystemLoader

from config import WEB_DIR, TMP_DIR
from eligibility import products, check_eligibility
import nvidia_llm


def _alternatives(prospect, current_product_id, k=3):
    """Other products the customer also qualifies for — cross-sell suggestions."""
    alts = []
    for pid in products():
        if pid == current_product_id:
            continue
        try:
            e = check_eligibility(prospect, pid)
        except Exception:
            continue
        if e["decision"] in ("eligible", "conditional") and e["offered_amount"] > 0:
            # suitability proxy = eligibility strength + affordability (NOT loan size / commission)
            afford = max(0.0, 1 - e["projected_foir"] / max(products()[pid]["max_foir"], 0.01))
            suit = (1.0 if e["decision"] == "eligible" else 0.5) + afford
            alts.append({"name": e["product_name"], "amount": e["offered_amount"],
                         "rate": e["rate"], "emi": e["emi"], "tenure": e["tenure_months"],
                         "_v": suit})
    alts.sort(key=lambda a: -a["_v"])
    return alts[:k]

# ensure WeasyPrint can find Homebrew libs even if launched without the env var
os.environ.setdefault("DYLD_FALLBACK_LIBRARY_PATH", "/opt/homebrew/lib")

_env = Environment(loader=FileSystemLoader(str(WEB_DIR / "templates")), autoescape=True)


def _copy(prospect, offer, use_llm):
    """intro paragraph + benefit bullets (LLM phrases; deterministic fallback)."""
    first = prospect["name"].split()[0]
    if use_llm and nvidia_llm.available():
        safe = nvidia_llm.deidentify(prospect)
        out = nvidia_llm.complete_json(
            "You write compliant, warm copy for an IDBI Bank loan offer letter. Use only "
            "provided facts; no guarantees/assured-return language.",
            f"Customer first name {first}. De-identified profile {safe}. Offer {offer}.\n"
            'Return {"intro":"<=45 words","benefits":["3-4 short bullets"]}.',
        )
        if out and out.get("intro") and out.get("benefits"):
            return out["intro"], out["benefits"][:4]
    intro = (f"Thank you for your interest in IDBI Bank. Based on your profile, we are pleased to "
             f"extend the following personalised, pre-approved indicative offer.")
    benefits = [
        f"Competitive {offer['rate']}% p.a. on a reducing-balance basis",
        f"Comfortable EMI of ₹{offer['emi']:,.0f} over {offer['tenure_months']} months",
        "Minimal documentation with a fully digital application journey",
        "Dedicated relationship manager support end-to-end",
    ]
    return intro, benefits


def generate_offer_pdf(prospect: dict, offer: dict, rm_name: str = "IDBI Relationship Team",
                       use_llm: bool = True) -> str:
    product = products()[offer["product_id"]]
    intro, benefits = _copy(prospect, offer, use_llm)

    r_monthly = offer["rate"] / 12 / 100
    total_repayable = offer["emi"] * offer["tenure_months"]
    processing_fee = round(offer["offered_amount"] * 0.005)

    ctx = {
        "ref": f"IDBI/PA/{prospect['id']}",
        "date": date(2026, 7, 6).strftime("%d %b %Y"),
        "rm_name": rm_name,
        "customer_name": prospect["name"],
        "first_name": prospect["name"].split()[0],
        "city": prospect.get("city", ""),
        "product_name": offer.get("product_name", product["name"]),
        "amount": int(offer["offered_amount"]),
        "rate": offer["rate"],
        "tenure_months": offer["tenure_months"],
        "emi": offer["emi"],
        "processing_fee": processing_fee,
        "total_repayable": total_repayable,
        "intro": intro,
        "benefits": benefits,
        "terms": [
            f"Offer is indicative and valid for 15 days from {date(2026,7,6).strftime('%d %b %Y')}.",
            "Final sanction is subject to CIBIL bureau check, KYC verification and IDBI credit policy.",
            f"Interest rate {offer['rate']}% p.a. on reducing balance; subject to reset per bank policy.",
            f"Processing fee ~0.5% (₹{processing_fee:,}) plus applicable GST.",
            "Prepayment/foreclosure charges as per the sanction letter and RBI guidelines.",
        ],
        "alternatives": _alternatives(prospect, offer["product_id"]),
        "next_steps": ["Confirm interest", "Share KYC & income proof", "e-Sign sanction"],
        "disclaimer": ("This document is an indicative offer generated by Prospect Assist AI and "
                       "is not a commitment to lend. Terms subject to verification and IDBI Bank policy."),
    }

    html = _env.get_template("offer.html").render(**ctx)
    from weasyprint import HTML
    out_path = TMP_DIR / f"offer_{prospect['id']}.pdf"
    HTML(string=html, base_url=str(WEB_DIR)).write_pdf(str(out_path))
    return str(out_path)


if __name__ == "__main__":
    from config import load_json
    from eligibility import check_eligibility
    p = load_json("prospects.json")[0]
    offer = check_eligibility(p, p["requested_product"])
    path = generate_offer_pdf(p, offer, use_llm=False)
    print("PDF written:", path, "->", os.path.getsize(path), "bytes")
